import React, {Component} from 'react';

class About extends Component {
    render(){
        return (
            <div className="about">
                <h3>My Name Alex</h3>
                <h4>Im an Electrical and Computational Engineering Student at UBC.</h4>
                <p>lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam maecenas sed enim ut sem viverra aliquet eget sit. Elit eget gravida cum sociis natoque penatibus et magnis dis. In massa tempor nec feugiat nisl. Ipsum faucibus vitae aliquet nec ullamcorper sit. Lectus arcu bibendum at varius vel pharetra vel turpis. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Convallis aenean et tortor at risus viverra adipiscing. Congue eu consequat ac felis donec. Eu volutpat odio facilisis mauris sit amet. Suscipit adipiscing bibendum est ultricies integer. Sed tempus urna et pharetra pharetra. Elementum curabitur vitae nunc sed velit dignissim sodales. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem.
                    Purus in mollis nunc sed id semper. Eget felis eget nunc lobortis mattis aliquam. Suscipit adipiscing bibendum est ultricies. Purus faucibus ornare suspendisse sed nisi lacus sed. Donec enim diam vulputate ut pharetra sit amet. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Turpis egestas sed tempus urna et pharetra pharetra massa. Porttitor eget dolor morbi non arcu risus. In cursus turpis massa tincidunt. Lorem dolor sed viverra ipsum nunc aliquet. Tempor orci dapibus ultrices in iaculis. Mi quis hendrerit dolor magna eget est lorem. Aliquam etiam erat velit scelerisque in dictum. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Ultricies tristique nulla aliquet enim tortor.</p>
                
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam maecenas sed enim ut sem viverra aliquet eget sit. Elit eget gravida cum sociis natoque penatibus et magnis dis. In massa tempor nec feugiat nisl. Ipsum faucibus vitae aliquet nec ullamcorper sit. Lectus arcu bibendum at varius vel pharetra vel turpis. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Convallis aenean et tortor at risus viverra adipiscing. Congue eu consequat ac felis donec. Eu volutpat odio facilisis mauris sit amet. Suscipit adipiscing bibendum est ultricies integer. Sed tempus urna et pharetra pharetra. Elementum curabitur vitae nunc sed velit dignissim sodales. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem.
                Purus in mollis nunc sed id semper. Eget felis eget nunc lobortis mattis aliquam. Suscipit adipiscing bibendum est ultricies. Purus faucibus ornare suspendisse sed nisi lacus sed. Donec enim diam vulputate ut pharetra sit amet. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Turpis egestas sed tempus urna et pharetra pharetra massa. Porttitor eget dolor morbi non arcu risus. In cursus turpis massa tincidunt. Lorem dolor sed viverra ipsum nunc aliquet. Tempor orci dapibus ultrices in iaculis. Mi quis hendrerit dolor magna eget est lorem. Aliquam etiam erat velit scelerisque in dictum. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Ultricies tristique nulla aliquet enim tortor.</p>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam maecenas sed enim ut sem viverra aliquet eget sit. Elit eget gravida cum sociis natoque penatibus et magnis dis. In massa tempor nec feugiat nisl. Ipsum faucibus vitae aliquet nec ullamcorper sit. Lectus arcu bibendum at varius vel pharetra vel turpis. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Convallis aenean et tortor at risus viverra adipiscing. Congue eu consequat ac felis donec. Eu volutpat odio facilisis mauris sit amet. Suscipit adipiscing bibendum est ultricies integer. Sed tempus urna et pharetra pharetra. Elementum curabitur vitae nunc sed velit dignissim sodales. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem.
                Purus in mollis nunc sed id semper. Eget felis eget nunc lobortis mattis aliquam. Suscipit adipiscing bibendum est ultricies. Purus faucibus ornare suspendisse sed nisi lacus sed. Donec enim diam vulputate ut pharetra sit amet. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Turpis egestas sed tempus urna et pharetra pharetra massa. Porttitor eget dolor morbi non arcu risus. In cursus turpis massa tincidunt. Lorem dolor sed viverra ipsum nunc aliquet. Tempor orci dapibus ultrices in iaculis. Mi quis hendrerit dolor magna eget est lorem. Aliquam etiam erat velit scelerisque in dictum. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Ultricies tristique nulla aliquet enim tortor.</p>
            </div>
            


        );
    }
}

export default About;